### PR TITLE
eliminate TypeError: iter() returned non-iterator of type'QueryableModelCollection' when using py3

### PR DESCRIPTION
**Pull request by deathowl**

### CODE REVIEW

**Comment by deathowl** [comment]
@jimbobhickville could you merge it please?

**Comment by jimbobhickville** [comment]
@deathowl Sorry, I never got notified that it this PR was submitted.  lgtm

**Comment by deathowl** [comment]
could you please also tag a version from the current master? So i wont have to use my fork and git+ url in  my requirements.txt. I'd be pretty thankful.

**Comment by jimbobhickville** [comment]
@deathowl https://pypi.python.org/pypi/python-ambariclient/0.5.9

**Comment by deathowl** [comment]
@jimbobhickville thanks it works well 👍

**Pull request merged**
